# Generated by Django 5.2.6 on 2026-04-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('image', models.URLField(max_length=500)),
                ('social_proof', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=255)),
                ('landlord', models.CharField(max_length=255)),
                ('rent', models.CharField(max_length=100)),
                ('blockchain_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('last_paid', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.property')),
            ],
        ),
    ]
